#!/usr/bin/env python3
"""Build or verify public-safe guide assets for external-data examples."""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
from pathlib import Path
import shutil
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from plots import example_assets  # noqa: E402
from plots import seattle_transit_impacts  # noqa: E402
from plots import westeros_example  # noqa: E402


FIGURES = ROOT / "docs" / "practitioner-guide" / "figures"
TABLES = ROOT / "docs" / "practitioner-guide" / "tables"
MANIFEST = TABLES / "external-example-assets.json"
TEX_MACROS = (
    ROOT / "docs" / "practitioner-guide" / "generated" /
    "external-example-results.tex"
)
GENERIC_STEMS = ("sioux",)
GENERIC_SUFFIXES = (
    "welfare-map.pdf",
    "welfare-map.png",
    "scatter.pdf",
    "scatter.png",
    "comparison.pdf",
    "comparison.png",
)
SEATTLE_ASSETS = {
    "seattle_aa_multimodal_network.pdf": "seattle-network.pdf",
    "seattle_aa_multimodal_network.png": "seattle-network.png",
    "seattle_aa_mode_welfare.pdf": "seattle-welfare-map.pdf",
    "seattle_aa_mode_welfare.png": "seattle-welfare-map.png",
    "seattle_transit_traditional_extended.pdf": "seattle-scatter.pdf",
    "seattle_transit_traditional_extended.png": "seattle-scatter.png",
    "seattle_combined_road_transit_welfare.pdf": "seattle-mode-map.pdf",
    "seattle_combined_road_transit_welfare.png": "seattle-mode-map.png",
}


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def read_rows(path: Path) -> list[dict[str, str]]:
    if not path.is_file():
        raise FileNotFoundError(path)
    with path.open(newline="", encoding="utf-8") as stream:
        return list(csv.DictReader(stream))


def float_field(row: dict[str, str], alternatives: tuple[str, ...]) -> float:
    for field in alternatives:
        value = row.get(field)
        if value not in (None, ""):
            return float(value)
    raise ValueError(f"none of {alternatives!r} is present")


def write_contract(
    destination: Path,
    nodes_path: Path,
    edge_modes_path: Path,
    results_path: Path,
) -> None:
    nodes = read_rows(nodes_path)
    edge_modes = read_rows(edge_modes_path)
    results = read_rows(results_path)
    destination.mkdir(parents=True, exist_ok=True)

    with (destination / "nodes.csv").open(
        "w", newline="", encoding="utf-8"
    ) as stream:
        writer = csv.writer(stream, lineterminator="\n")
        writer.writerow(("node_id", "x", "y", "activity", "terminal"))
        for row in nodes:
            first = float_field(row, ("labor", "residence"))
            second = float_field(row, ("income", "workplace"))
            writer.writerow((
                row["node_id"],
                f"{float(row['longitude']):.17g}",
                f"{float(row['latitude']):.17g}",
                f"{0.5 * (first + second):.17g}",
                "false",
            ))

    modes_by_link: dict[str, set[str]] = {}
    for row in edge_modes:
        if float(row["flow"]) <= 0:
            continue
        modes_by_link.setdefault(row["physical_link_id"], set()).add(row["mode"])

    with (destination / "links.csv").open(
        "w", newline="", encoding="utf-8"
    ) as stream:
        writer = csv.writer(stream, lineterminator="\n")
        writer.writerow((
            "physical_link_id", "endpoint_a", "endpoint_b",
            "hulten", "primitive_F", "modes",
        ))
        for row in sorted(results, key=lambda item: item["physical_link_id"]):
            identifier = row["physical_link_id"]
            writer.writerow((
                identifier,
                row["endpoint_a"],
                row["endpoint_b"],
                f"{float(row['hulten']):.17g}",
                f"{float(row['primitive_F']):.17g}",
                "|".join(sorted(modes_by_link[identifier])),
            ))


def write_seattle_table(source: Path, destination: Path) -> None:
    rows = read_rows(source)
    grouped: dict[str, list[dict[str, str]]] = {}
    for row in rows:
        grouped.setdefault(row["mode"], []).append(row)
    selected: list[dict[str, str]] = []
    for mode in ("road", "bus", "rail", "ferry"):
        ordered = sorted(
            grouped.get(mode, []),
            key=lambda row: (-float(row["extended_gain_pct"]), row["corridor_id"]),
        )
        selected.extend(ordered[:3])

    lines = [
        "% Generated by scripts/build_practitioner_external_example_assets.py.",
        r"\begin{tabular}{llrrrr}",
        r"\toprule",
        r"Corridor & Mode & Traditional & Extended & Traditional rank & Extended rank \\",
        r"\midrule",
    ]
    for row in selected:
        corridor = row["corridor_id"].replace("_", r"\_")
        lines.append(
            f"{corridor} & {row['mode']} & "
            f"{float(row['traditional_gain_pct']):.6f} & "
            f"{float(row['extended_gain_pct']):.6f} & "
            f"{int(float(row['traditional_rank']))} & "
            f"{int(float(row['extended_rank']))} \\\\"
        )
    lines.extend((r"\bottomrule", r"\end{tabular}", ""))
    destination.write_text("\n".join(lines), encoding="utf-8")


def write_external_macros(inputs: dict[str, Path]) -> None:
    def result_summary(path: Path) -> dict[str, float]:
        rows = read_rows(path)
        traditional = [float(row["hulten"]) for row in rows]
        extended = [float(row["primitive_F"]) for row in rows]
        pearson, spearman = example_assets.style.correlations(
            traditional, extended
        )
        return {
            "links": len(rows),
            "mean_traditional": sum(traditional) / len(traditional),
            "mean_extended": sum(extended) / len(extended),
            "pearson": pearson,
            "spearman": spearman,
        }

    sioux_build = json.loads(
        inputs["sioux_manifest"].read_text(encoding="utf-8")
    )
    westeros_build = json.loads(
        inputs["westeros_summary"].read_text(encoding="utf-8")
    )
    seattle_build = json.loads(
        inputs["seattle_manifest"].read_text(encoding="utf-8")
    )
    sioux_results = result_summary(inputs["sioux_results"])
    westeros_results = result_summary(inputs["westeros_results"])
    seattle_summary = {
        row["mode"]: row
        for row in read_rows(inputs["seattle_summary"])
    }

    def number(value: float, digits: int = 6) -> str:
        return f"{value:.{digits}f}"

    pairs = {
        "GuideSiouxNodeCount": str(sioux_build["nodes"]),
        "GuideSiouxDirectedArcCount": str(sioux_build["directed_links"]),
        "GuideSiouxPhysicalLinkCount": str(sioux_build["physical_links"]),
        "GuideSiouxMeanTraditional":
            number(sioux_results["mean_traditional"]),
        "GuideSiouxMeanExtended": number(sioux_results["mean_extended"]),
        "GuideSiouxPearson": number(sioux_results["pearson"], 3),
        "GuideSiouxSpearman": number(sioux_results["spearman"], 3),
        "GuideWesterosNodeCount": str(westeros_build["occupied_settlements"]),
        "GuideWesterosDirectedArcCount": str(westeros_build["directed_arcs"]),
        "GuideWesterosPhysicalLinkCount":
            str(westeros_build["active_physical_links"]),
        "GuideWesterosMeanTraditional":
            number(westeros_results["mean_traditional"]),
        "GuideWesterosMeanExtended":
            number(westeros_results["mean_extended"]),
        "GuideWesterosPearson": number(westeros_results["pearson"], 3),
        "GuideWesterosSpearman": number(westeros_results["spearman"], 3),
        "GuideSeattleNodeCount": "217",
        "GuideSeattleRoadArcCount":
            seattle_summary["road"]["directed_interventions"],
        "GuideSeattleBusArcCount":
            seattle_summary["bus"]["directed_interventions"],
        "GuideSeattleRailArcCount":
            seattle_summary["rail"]["directed_interventions"],
        "GuideSeattleFerryArcCount":
            seattle_summary["ferry"]["directed_interventions"],
        "GuideSeattleBusMeanExtended":
            number(float(seattle_summary["bus"]["mean_extended_gain_pct"])),
        "GuideSeattleRailMeanExtended":
            number(float(seattle_summary["rail"]["mean_extended_gain_pct"])),
        "GuideSeattleFerryMeanExtended":
            number(float(seattle_summary["ferry"]["mean_extended_gain_pct"])),
        "GuideSeattleBusSpearman":
            number(float(seattle_summary["bus"]["spearman"]), 3),
        "GuideSeattleRailSpearman":
            number(float(seattle_summary["rail"]["spearman"]), 3),
        "GuideSeattleFDMaximum":
            f"{seattle_build['finite_difference_max_error'] / 1e-11:.2f}"
            r"\times 10^{-11}",
    }
    TEX_MACROS.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "% Generated by scripts/build_practitioner_external_example_assets.py."
    ]
    lines.extend(
        f"\\providecommand{{\\{name}}}{{{value}}}"
        for name, value in pairs.items()
    )
    TEX_MACROS.write_text("\n".join(lines) + "\n", encoding="utf-8")


def copy_generic_assets(source_figures: Path, source_tables: Path) -> list[Path]:
    outputs: list[Path] = []
    FIGURES.mkdir(parents=True, exist_ok=True)
    TABLES.mkdir(parents=True, exist_ok=True)
    for stem in GENERIC_STEMS:
        for suffix in GENERIC_SUFFIXES:
            source = source_figures / f"{stem}-{suffix}"
            target = FIGURES / source.name
            shutil.copyfile(source, target)
            outputs.append(target)
        for suffix in ("top-links.tex", "link-comparison.csv"):
            source = source_tables / f"{stem}-{suffix}"
            target = TABLES / source.name
            shutil.copyfile(source, target)
            outputs.append(target)
    return outputs


def build(args: argparse.Namespace) -> None:
    sioux = args.sioux_root.resolve()
    westeros = args.westeros_root.resolve()
    seattle_artifacts = args.seattle_artifacts.resolve()
    seattle_model = args.seattle_model_root.resolve()
    inputs = {
        "sioux_nodes": sioux / "generated" / "nodes.csv",
        "sioux_edges": sioux / "generated" / "edge_modes.csv",
        "sioux_results": sioux / "output-extended" / "decomposition_physical.csv",
        "sioux_manifest": sioux / "generated" / "build_manifest.json",
        "westeros_nodes": westeros / "data" / "nodes.csv",
        "westeros_edges": westeros / "data" / "edge_modes.csv",
        "westeros_results": westeros / "output" / "decomposition_physical.csv",
        "westeros_summary": args.westeros_root.resolve() / "network_summary.json",
        "westeros_continent":
            westeros / "source_cache" / "continent.geojson",
        "westeros_roads": westeros / "source_cache" / "roads.geojson",
        "westeros_link_geometry": westeros / "link_geometry.geojson",
        "seattle_nodes": seattle_model / "data" / "nodes.csv",
        "seattle_edges": seattle_model / "data" / "edge_modes.csv",
        "seattle_manifest": seattle_artifacts / "artifact_manifest.json",
        "seattle_summary": seattle_artifacts / "summary.csv",
        "seattle_links": seattle_artifacts / "top30_links.csv",
    }
    for path in inputs.values():
        if not path.is_file():
            raise FileNotFoundError(path)

    with tempfile.TemporaryDirectory(
        prefix="tnw-guide-external-examples-"
    ) as temporary_name:
        temporary = Path(temporary_name)
        contracts = temporary / "contracts"
        write_contract(
            contracts / "sioux",
            inputs["sioux_nodes"], inputs["sioux_edges"], inputs["sioux_results"],
        )
        generic_figures = temporary / "generic-figures"
        generic_tables = temporary / "generic-tables"
        example_assets.build_assets(
            contracts, generic_figures, generic_tables, GENERIC_STEMS
        )
        outputs = copy_generic_assets(generic_figures, generic_tables)
        outputs.extend(
            westeros_example.build_assets(westeros, FIGURES, TABLES)
        )
        for obsolete in (
            "westeros-comparison.pdf",
            "westeros-comparison.png",
            "westeros-welfare-map.pdf",
            "westeros-welfare-map.png",
        ):
            (FIGURES / obsolete).unlink(missing_ok=True)

        seattle_temporary = temporary / "seattle"
        seattle_temporary.mkdir()
        for source in seattle_artifacts.iterdir():
            if source.is_file() and source.suffix in (".csv", ".json", ".geojson"):
                shutil.copyfile(source, seattle_temporary / source.name)
        seattle_transit_impacts.build_figures(
            seattle_temporary,
            inputs["seattle_nodes"],
            args.seattle_geography_root.resolve(),
            edge_modes_path=inputs["seattle_edges"],
            gtfs_root=args.seattle_gtfs_root.resolve(),
            observed_roads=seattle_temporary / "aa_observed_roads.geojson",
        )
        for source_name, target_name in SEATTLE_ASSETS.items():
            target = FIGURES / target_name
            shutil.copyfile(seattle_temporary / source_name, target)
            outputs.append(target)
        seattle_table = TABLES / "seattle-top-links.tex"
        write_seattle_table(inputs["seattle_links"], seattle_table)
        outputs.append(seattle_table)
        write_external_macros(inputs)
        outputs.append(TEX_MACROS)

    metadata = {
        "schema_version": 1,
        "status": {
            "sioux_falls": "verified_external_data",
            "seattle_multimodal": "verified_candidate_application",
            "westeros": "verified_synthetic_external_geography",
        },
        "construction": {
            "sioux_falls":
                "balanced TNTP OD margins and reciprocal assigned flows; "
                "heterogeneous local BPR elasticities",
            "seattle_multimodal":
                "2017 LODES OD, 2017 ACS origin mode shares, pinned June 2017 "
                "GTFS paths and schedules, Allen-Arkolakis road times",
            "westeros":
                "hash-pinned ArcGIS geography, synthetic economic activity, "
                "balanced gravity trade, shortest-path routing",
        },
        "input_hashes": {
            name: sha256(path) for name, path in sorted(inputs.items())
        },
        "output_hashes": {
            str(path.relative_to(ROOT)): sha256(path)
            for path in sorted(outputs)
        },
    }
    MANIFEST.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST.write_text(
        json.dumps(metadata, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    print(MANIFEST.relative_to(ROOT))


def check() -> None:
    if not MANIFEST.is_file():
        raise FileNotFoundError(MANIFEST)
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    for relative, expected in manifest["output_hashes"].items():
        path = ROOT / relative
        if not path.is_file():
            raise FileNotFoundError(path)
        observed = sha256(path)
        if observed != expected:
            raise RuntimeError(
                f"external example asset drift: {relative}: "
                f"{observed} != {expected}"
            )
    print("external-data practitioner-guide assets accepted")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--sioux-root", type=Path)
    parser.add_argument("--westeros-root", type=Path)
    parser.add_argument("--seattle-artifacts", type=Path)
    parser.add_argument("--seattle-model-root", type=Path)
    parser.add_argument("--seattle-geography-root", type=Path)
    parser.add_argument("--seattle-gtfs-root", type=Path)
    args = parser.parse_args()
    if not args.check:
        missing = [
            name for name in (
                "sioux_root", "westeros_root", "seattle_artifacts",
                "seattle_model_root", "seattle_geography_root",
                "seattle_gtfs_root",
            )
            if getattr(args, name) is None
        ]
        if missing:
            parser.error(
                "building external assets requires " +
                ", ".join("--" + name.replace("_", "-") for name in missing)
            )
    return args


if __name__ == "__main__":
    arguments = parse_args()
    check() if arguments.check else build(arguments)
